### ISSUE TITLE
Any plans to update this gem?

### ISSUE THREAD

**Issue by ijdickinson** [ministryofjustice/govuk_elements_rails#4]
This looks like a really easy way to pull GOV.UK Elements into a project, but it's now rather behind the current head of the Elements repo. Do you have any plans to update and make a new release?

**Comment by robmckinnon** [comment]
Thanks for expressing interest in the gem. We've had a team discussion about this today. We're hopefully going to find the time to update it.

**Comment by robmckinnon** [comment]
Pull request for update is here: https://github.com/ministryofjustice/govuk_elements_rails/pull/6

Plan is to release after it's reviewed.
